### CONFIGURATION SERVER ###
server:
  port: 8080

### CONFIGURATION DATABASE ###
spring:
  output:
    ansi:
      enabled: ALWAYS
  data:
    mongodb:
      uri: mongodb://root:toor@localhost:27017/admin
      auto-index-creation: true

#CONFIGURATION LOG
logging:
  level:
    root: INFO
    com:
      example: TRACE

# SWAGGER
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
    operationsSorter: method

# ACTUATOR
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info
  info:
    env:
      enabled: true

# INFORMATION
info:
  app:
    name: "user-example-service"
    description: "User example service"
  author: "Jhow"
  java-version: ${java.version}